### ISSUE TITLE
Possible Update

### ISSUE THREAD

**Issue by tonyrayo** [shawly/docker-ps3netsrv#1]
Hi, I was wondering if it'd be possible to update the container to use the latest version (which seems to be [2019-09-24](https://github.com/aldostools/webMAN-MOD/releases/download/1.47.25/ps3netsrv_20190924.zip) at the moment. If not, I will have time this weekend to examine the files and possibly fork/update/PR (especially if it's just a matter of copying new src files).  Cheers!

**Comment by shawly** [comment]
Oh sure, give me time until weekend, I'll update it!

**Comment by shawly** [comment]
Hey sorry for the huge delay, but I finally found some time to upgrade the binary, but I haven't yet tested if it works properly since my PS3 isn't hooked up currently. 
I'd appreciate if you could test if it works so I can close the ticket. :)

**Edit** NVM it's missing some libs.
**Edit2** Ok fixed the issue where libraries from the build container wouldn't match the alpine ones. Now it should work properly. I'm closing the ticket for now, please tell me if there is anything that isn't working properly.
