### ISSUE TITLE
Help installing in UnRaid?

### ISSUE THREAD

**Issue by Ibbanez** [shawly/docker-ps3netsrv#3]
*** Actually, one sec, testing something, I think its working, but might be something else on my end.  Will update shortly. ***

Hello there.  I was wondering if you could help point me in the right direction of getting this running on Unraid.  I installed the docker and added the port as 38008, made a path variable called /games and pointed it to my ps3iso directory, but I still have nothing.  Any help would be greatly appreciated.  Thanks.

**Comment by shawly** [comment]
Make sure you set the correct uid and gid environment variables reflecting the ownership of your ps3iso directory or change the ownership of your ps3iso directory to 1000:1000.
If your PS3 can connect to the ps3netsrv but you don't see anything in your net0: drive it's usually an ownership issue, if you can't connect even though the port is open it's probably a networking issue and not related to the docker container.

I don't have an UnRaid installation so it's difficult for me to perceive what you did and how you've configured your container, so a screenshot and/or your config might help me understand what could be the issue here.

**Comment by Ibbanez** [comment]
Thanks for responding.  When I pull the log, it shows this

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-adduser: executing...
usermod: no changes

-------------------------------------
GID/UID
-------------------------------------

User uid: 1000
User gid: 1000
-------------------------------------

[cont-init.d] 00-adduser: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

Now, when I enter the console, and goto the /games directory, it shows all my isos.  So i feel like that part is working correctly.  I setup webman to scan lan and pointed it to my forwarded docker container address and port.  This is the only thing I think might be getting held up.  So I think I have the data path in unraid added, im still not sure they are talking to each other correctly, as no games appear when I go into IrisMan and search network games.  Im going to keep at this, and see.  Was just trying to run as a docker versus setting up a Windows VM just to serve this folder.  Thanks again.  Any thoughts and Im open to suggestions.

**Comment by shawly** [comment]
So if you go into the console, navigate into the /games directory and execute **ls -l**, who is owning the folders inside the /games directory?

It should look like this:

```shell
/ # ls -l /games
total 350
drwxrwx--- 119 ps3netsrv ps3netsrv 119 Mar  4  2019 GAMES
drwxrwx---   2 ps3netsrv ps3netsrv 215 Mar 17  2019 PS2ISO
drwxrwx---   7 ps3netsrv ps3netsrv   7 Jun 21  2019 PS3ISO
drwxrwx---   2 ps3netsrv ps3netsrv 420 Oct  5  2019 PSXISO
```

If it doesn't look like that, then it's an ownership issue.

**Comment by Ibbanez** [comment]
ok one sec...

**Comment by Ibbanez** [comment]
It shows this 

-rw-rw-rw- 1 99 users  5249105920 Dec  7 03:04 'skate. [BLES00124].iso'

I must admit, Im not a big linux user, so while I can google stuff, this isn't natural for me, but I can follow directions, and I know linux basics.

**Comment by Ibbanez** [comment]
And it shows that with all games.  Another questions, I have like almost 1000 titles.  Does it search for them all before showing any?  Im goiong to let it run a bit while i take my kids to the park really quick, but I'll be back shortly to respond to ya.  Also, my total was this

total 6895306304

**Comment by shawly** [comment]
> It shows this
> 
> -rw-rw-rw- 1 99 users 5249105920 Dec 7 03:04 'skate. [BLES00124].iso'
> 

Ok there is the problem, you didn't mount the correct folder. You shouldn't mount the PS3ISO folder into the container you have to mount the folder which **contains** your PS3ISO directory.

If you execute `ls -l /games` your folder structure has to look like this in your container:

```shell
/ # ls -l /games
total 350
drwxrwx--- 119 ps3netsrv ps3netsrv 119 Mar  4  2019 GAMES
drwxrwx---   2 ps3netsrv ps3netsrv 215 Mar 17  2019 PS2ISO
drwxrwx---   7 ps3netsrv ps3netsrv   7 Jun 21  2019 PS3ISO
drwxrwx---   2 ps3netsrv ps3netsrv 420 Oct  5  2019 PSXISO
```

Ownership shouldn't be an issue since everyone can read and write your folder, which might be a security concern though.

**Comment by Ibbanez** [comment]
Ahhh...I’ll bring it back a folder when I get back in about 10 mins and test. Thanks for spotting that.

**Comment by Ibbanez** [comment]
next question, does the folder that houses the iso's, must it be called PS3ISO?

**Comment by shawly** [comment]
Yes

**Comment by Ibbanez** [comment]
Ok, so thanks for everything, now webman lists the games, however if I load irisman, it crashes the ps3 to where I have to plug in a usbcable into the controller to restart the system. Any thoughts?

**Comment by Ibbanez** [comment]
And if I try to refresh webman games, it seems to crash, but if I view the games through setup, they must, but it only says 180 games versus the over 900 I have. Well I’m getting closer, but we shall see.

**Comment by shawly** [comment]
Dunno I only use WebMAN, never used Irisman. A thousand games might be a lot for the PS3, but all in all you should probably ask Aldostools about ps3netsrv and WebMAN specifics, I only created the docker image. ;)

**Comment by Ibbanez** [comment]
Thanks, for everything.  You were a huge help.  I may just say screw it and go back to running an 8tb ntfs drive for all those ISO's, but I wanted to give this a shot.  I'll keep playing and reach out to Aldostools.

**Comment by shawly** [comment]
You might wann read this https://github.com/aldostools/webMAN-MOD/issues/179

**Comment by BenDaMAN303** [comment]
Hey
Any ideas why ISOs would work being served by unraid with this docker, but folder format games won't load. The games' name and icon loads, but it just shows "corrupted data" item in the XMB when i load a folder format game with webman.

Permissions are definitely set correctly, with the user id 1000 being owner, and id 100 being the group.

**Comment by shawly** [comment]
No idea, maybe the game files are indeed corrupted? Maybe the permissions **within** your game folders are wrong? Dunno.

https://github.com/aldostools/webMAN-MOD/issues/333 they have the same issue.

aldostools updated ps3netsrv so I'll update the binaries in my image tomorrow as well, maybe that will fix the issue.

**Edit:** Ok I just updated the image, please try again. If it still doesn't work, please confirm that your issue is really related to my Docker image.

**Comment by BenDaMAN303** [comment]
Ah yes, looks like the exact same issue. So odd.

I have done the following in the /games mount folder, to ensure that all files & folders have the correct attributes:
chmod -R 777 *
chown -R 1000 *
chgrp -R 100 *

If i convert any given folder format games to ISO they mount and work correctly, the folder games also work when FTP'd over to the hdd. So definitely no corruption in the games themselves.

I will try again and get back to you.

**Comment by shawly** [comment]
I'm kinda guessing that this might be a problem with REBUG 4.86.1+ps3netsrv combination itself, as the guy who created the issue I linked, used a way older version of ps3netsrv and probably didn't use my Docker image.

My PS3 is still on REBUG 4.84.x or so as I haven't updated it in a while, I'll fire it up tomorrow and try this out myself, since all my games are in folder format I should be able to reproduce this issue, at least if the new ps3netsrv version didn't fix the issue already.

**Comment by BenDaMAN303** [comment]
Okay, so it looks like it's related to this mentioned here.
https://github.com/aldostools/webMAN-MOD/issues/345#issuecomment-631069794
I can see that it should be fixed with the new release.

When going here: https://hub.docker.com/r/shawly/ps3netsrv/builds
I'm only seeing tag v1.3.0, which was 2 months ago. So i'm assuming it's just under the :latest tag?

**Comment by shawly** [comment]
You have to look under tags: https://hub.docker.com/r/shawly/ps3netsrv/tags

1.4.1 is the latest

**Comment by shawly** [comment]
@BenDaMAN303 did you have any success?

I just tested it on my 4.81.2 REBUG system and it worked without any problems, I'm just updating it to REBUG 4.84.2 and latest webMAN-MOD and will try it again.

**Comment by BenDaMAN303** [comment]
Tried the new docker version and no luck whatsoever. I ended up rolling
back from REBUG 4.86.1 to REBUG 4.84.2 and folder format games still don't
work for me. Latest version of WebMAN-MOD.
What Linux distro are you using?

Tried latest ps3netsrv running on Windows 10, and both folder format and
ISO work there. I am thinking ps3netsrv is perhaps failing to create it's
virtual iso structure when running in the docker container on unraid
(v6.8.3).

**Comment by shawly** [comment]
So I just installed REBUG 4.84.2 and I can load folder format games still without any problems.

I'm using a simple Ubuntu host for my Docker containers and the files are served through an NFS share on my FreeNAS.

I'm not quite sure what the issue here may be, but now we can at least rule out the firmware. It seems like this might be related to UnRAID itself or it's still related to permissions.
You made sure to add the right USER_ID & GROUP_ID environment variables to your container? (I'm guess you did but I wanna be certain)

**Edit:** @BenDaMAN303 so I finally got UnRAID working and I can actually reproduce this issue with corrupted folder games as well. I'm trying to figure out what the actual issue is here, I'll update my progress here https://github.com/aldostools/webMAN-MOD/issues/333 if I find something out.
Found the issue and I found a workaround, I posted the info over in the other issue on the webMAN-MOD repo I linked.
